version: 2
jobs:
 build/firefly-server:0.5:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t $DOCKER_USER/firefly-server:0.5 firefly-server/0.5/

     # deploy the image
     - run: docker push $DOCKER_USER/firefly-server:0.5
 
 build/firefly-server:0.5bis:
   machine: true
   steps:
     - checkout
     # start proprietary DB using private Docker image
     # with credentials stored in the UI
     - run: docker login -u $DOCKER_USER -p $DOCKER_PASS

     # build the application image
     - run: docker build -t $DOCKER_USER/firefly-server:0.5 firefly-server/0.5/

     # deploy the image
     - run: docker push $DOCKER_USER/firefly-server:0.5
