####
# Inspired from two circle ci configurations :
# - https://github.com/decidim/decidim/pull/2028/files
# - https://gist.github.com/naesheim/18d0c0a58ee61f4674353a2f4cf71475
#
# The purpose here is to trigger a build only if a specific folder has been modified.
####

version: 2
jobs:
  firefly-api-base:0.1:
    machine: true
    environment:
      - FOLDER: "firefly-api-base"
      - VERSION: 0.1
    steps:
      - checkout
      
      # login to docker hub registry
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker login -u $DOCKER_USER -p $DOCKER_PASS"
      
      # build the application image
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker build -t $DOCKER_USER/$FOLDER:$VERSION $FOLDER/$VERSION/"

      # deploy the image
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker push $DOCKER_USER/$FOLDER:$VERSION"

  firefly-database-base:0.1:
    machine: true
    environment:
      - FOLDER: "firefly-database-base"
      - VERSION: 0.1
    steps:
      - checkout
 
      # login to docker hub registry
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker login -u $DOCKER_USER -p $DOCKER_PASS"

      # build the application image
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker build -t $DOCKER_USER/$FOLDER:$VERSION $FOLDER/$VERSION/"
 
      # deploy the image
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker push $DOCKER_USER/$FOLDER:$VERSION"

  firefly-api-base-sonar:0.1:
    machine: true
    environment:
      - FOLDER: "firefly-api-base-sonar"
      - VERSION: 0.1

    steps:
      - checkout
      
      # login to docker hub registry
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker login -u $DOCKER_USER -p $DOCKER_PASS"

      # build the application image
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker build -t $DOCKER_USER/$FOLDER:$VERSION $FOLDER/$VERSION/"

      # deploy the image
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker push $DOCKER_USER/$FOLDER:$VERSION"

  fly-base:0.1:
    machine: true
    environment:
      - FOLDER: "fly-base"
      - VERSION: 0.1

    steps:
      - checkout
      
      # login to docker hub registry
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker login -u $DOCKER_USER -p $DOCKER_PASS"

      # build the application image
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker build -t $DOCKER_USER/$FOLDER:$VERSION $FOLDER/$VERSION/"

      # deploy the image
      - run: bash .circleci/if_folder_has_changed.sh $FOLDER/$VERSION "docker push $DOCKER_USER/$FOLDER:$VERSION"

workflows:
  version: 2
  build-deploy-all:
    jobs:
      - fly-base:0.1
      - firefly-api-base:0.1
      - firefly-database-base:0.1
      - firefly-api-base-sonar:0.1:
          requires:
            - firefly-api-base:0.1

